### ISSUE TITLE
clean github history

### ISSUE THREAD

**Issue by tfjmp** [ProvTools/provR#20]
Remove large .jar file from the history.

**Comment by MKLau** [comment]
Use bfg to remove from entire commit history in provtools/provr

**Comment by MKLau** [comment]
Waiting for check of cleanup branch

**Comment by MKLau** [comment]
It failed to complete the removal.

I'm getting the error discussed in this post:

https://github.com/rtyley/bfg-repo-cleaner/issues/36

**Comment by MKLau** [comment]
Done.
