### ISSUE TITLE
Remove internal capture

### ISSUE THREAD

**Issue by MKLau** [ProvTools/provR#55]
This may be a block to CRAN.

Additionally, there are currently to user driven applications.

**Comment by blernermhc** [comment]
Clarifying that this means internal to functions and control constructs.

I agree that we should remove this at least for now.  The interactions between these 2 features are the buggiest parts of RDT and we should re-think how to do that if we want to restore those features later.

**Comment by MKLau** [comment]
Great, then this is a go to remove.
