### ISSUE TITLE
Remove intermediate capture

### ISSUE THREAD

**Issue by MKLau** [ProvTools/provR#56]
This creates non-trivial provR code and memory overhead. Also, currently, no user driven features require this.

**Comment by erboose** [comment]
Script debugging would require capturing intermediate data values.  Potential users at the ESA meeting last summer expressed an interest in using our tools for this purpose.

**Comment by MKLau** [comment]
This is also a go, based on where we got to in the meeting this morning.

Given the interest in their potential for a debugging tool to use this, we should keep in mind the future development of intermediate value capture once we have a well deformed and designed user driven feature.

**Comment by MKLau** [comment]
Now duplicated by Issue #50
