### ISSUE TITLE
Value size seems off

### ISSUE THREAD

**Issue by tfjmp** [ProvTools/provR#67]
For example: "rdt:value" : "\"sampleCode = 1  \"",
"rdt:valType" : {"container":"vector", "dimension":[1], "type":["character"]},

I would not expect dimension to be 1 here, though?

**Comment by MKLau** [comment]
That makes sense to me. Vectors are of one dimension. Matrices are of two dimensions, arrays are of n dimensions.

**Comment by tfjmp** [comment]
Oki ty Matt closing.
