### ISSUE TITLE
json parse error from cleanR

### ISSUE THREAD

**Issue by MKLau** [ProvTools/provR#68]
This is for the tfjmp@capture pull request.

Error: parse error: unallowed token at this point in JSON text
          : "", "rdt:sourcedScripts" : , "rdt:scriptTimeStamp" : "", "
                     (right here) ------^
In addition: Warning message:
In .ddg.insert.error.message(error.msg) :
  No binding for ddg.start.time . DDG may be incorrect!

**Comment by tfjmp** [comment]
Can you check that it does not happened with the master branch?

Can you post the whole JSON output?

Also could you come up with a few lines of scripts so we can add cleanR regression test to the automated test?

Thanks!

**Comment by MKLau** [comment]
Looks like this is a combination of the prov.json not being empty intially and cleanR not correctly initializing.

**Comment by tfjmp** [comment]
Any progress on getting the data?

**Comment by MKLau** [comment]
Sorry, I should have closed this after my last comment. It's a cleanR issue, I need to adjust the API.

**Comment by tfjmp** [comment]
Did you do: Also could you come up with a few lines of scripts so we can add cleanR regression test to the automated test?

**Comment by MKLau** [comment]
No, but it's on my desk to add this to the cleanR issue system

**Comment by MKLau** [comment]
Hopefully, I'll get to it tomorrow afternoon

**Comment by MKLau** [comment]
The issue itself, that is. I'll just go add this to cleanR now
